// <auto-generated />
namespace LookaukwatApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class isdeletebyuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isdeletebyuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202102201247466_isdeletebyuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
